config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root 'top#index'
  resources :users, only: [:index, :show]
  resources :list, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :card do
      put :sort
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @lists = List.where(user: current_user).order("created_at ASC")
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/index.html.erb
<div class="topPage">
  <div class="listWrapper">
    <% @lists.each do |list| %>
      <div class="list sortable_list">
        <div class="list_header">
          <h2 class="list_header_title"><%= list.title %></h2>
          <div class="list_header_action">
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: { confirm: "#{list.title}を削除しても大丈夫ですか？"} %>
            <%= link_to content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list) %>
          </div>
        </div>

        <div class="cardWrapper">
          <table>
            <% list.cards.each do |card| %>
              <tr class="item" data-model-name="card", data-update-url=<%="/list/#{list.id}/card/#{card.id}/sort"%>>
                <% if card.status == "未実施" %>
                  <td class="item__status item__status--yet">
                <% elsif card.status == "実施中" %>
                  <td class="item__status item__status--now">
                <% else %>
                  <td class="item__status item__status--done">
                <% end %>
                  <%= card.status %>
                  </td>
                <td class="col-12">
                  <%= link_to list_card_path(list, card), class: "cardDetail_link" do %>
                    <div class="card">
                      <h3 class="card_title">
                        <%= card.title %>
                      </h3>
                      <% if card.memo.size > 0 %>
                        <div class="card_detail is-exist">
                          <i class="fas fa-bars"></i>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
            
          <div class="addCard">
            <i class="far fa-plus-square"></i>
            <%= link_to "さらにカードを追加", new_list_card_path(list), class: "addCard_link" %>
          </div>
        </div>

      </div>
    <% end %>
  </div>
  <%# <div class="chart">
      <%= pie_chart @chart %>
  <%# </div> %>
</div>