config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root 'top#index'
  resources :users, only: [:index, :show]
  resources :list, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :card do
      put :sort
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  
  validates :title, length: { in: 1..255 }
  validates :memo,  length: { maximum: 1000 }
  
  include RankedModel
  ranks :row_order
  
  enum status: {
    "未実施": "0",
    "実施中": "1",
    "達成": "2"
  }

end  

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  
  def index
    @cards = Card.rank(:row_order)
  end
  
  def new
    @card = Card.new
    @list = List.find_by(id: params[:list_id])
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def show
  end

  def edit
    @lists = List.where(user: current_user)
    @statuses = Card.where(user: current_user)
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to :root
  end

  def sort
    card = Card.find(params[:card_id])
    card.update(card_params)
    render body: nil
  end

  private
    def card_params
      params.require(:card).permit(:title, :memo, :list_id, :status, :row_order_position)
    end

    def set_card
      @card = Card.find_by(id: params[:id])
    end
    
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/create.html.erb
<h1>Card#create</h1>
<p>Find me in app/views/card/create.html.erb</p>

app/views/card/edit.html.erb
<div class="cardeditPage">
  <div class="container">
    <%= form_with model: @card, url: { action: :update }, html: { class: "cardeditForm" }, local: true do |f| %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1〜255文字以内で入力してください</p>
      <% end %>

      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "カード名" %>
      </div>
      
      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_field :memo, class: "form-control", placeholder: "詳細" %>
      </div>

      <div class="cardeditForm_list">
        <label>リスト名</label>
        <%= select :card, :list_id, @lists.map{ |l| [l.title, l.id ] }, {}, { class: "form-control" } %>
      </div>

      <div class="cardeditForm_status">
        <label>ステータス</label>
        <%= select :card, :status, Card.statuses.keys, {selected: @card.status}, {class: "form-control"} %>
      </div>

      <div class="text-center"> <%= f.submit "更新する", class: "submitBtn" %> </div>
    <% end %>
  </div>
</div>

app/views/card/new.html.erb
<div class="cardnewPage">
  <div class="container">
    <%= form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
      <%= f.hidden_field :list_id, value: @list.id %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1〜255文字以内で入力してください</p>
      <% end %>
      <div class="cardnewForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardnewForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細" %>
        <div class="text-center">
          <%= f.submit "作成する", class: "submitBtn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/card/show.html.erb
<div class="carddetailPage">
  <div class="container">
    <div class="cardContents">

      <div class="cardContents_title">
        <div>タイトル</div>
        <h2> <%= @card.title %> </h2>
      </div>
      
      <div class="cardContents_memo">
        <div>メモ</div>
        <div> <%= @card.memo %> </div>
      </div>
      
      <div class="cardContents_listStatus">
        <div>リスト名</div>
        <div> <%= @card.list.title %> </div>
      </div>

      <div class="cardContents_cardStatus">
        <div>ステータス</div>
        <div> <%= @card.status %> </div>
      </div>

      <div class="cardContents_btnArea">
        <%= link_to "編集する", edit_list_card_path(@card.list, @card), class: "edit_btn" %>
        <%= link_to "削除する", list_card_path(@card.list, @card), class: "text-danger delete_btn", method: :delete, data: { confirm: "このカードを削除して大丈夫ですか？" } %>
      </div>
      
    </div>
  </div>
</div>